---
#- hosts: master
#  become: yes
#  become_method: sudo
#  tags:
#  - helm_reset
#  - helm
#  - reset
#  tasks:

- set_fact:
    env_kc: '{{ proxy_env |default({}) | combine ({"PATH" : "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin"  }) | combine ({"KUBECONFIG" :"/etc/kubernetes/admin.conf"}) }}'
  tags:
  - helm_reset
  - reset
  - helm_purge

- block:
  - name: helm list all apps
    environment: '{{env_kc}}'
    shell: helm list | tail -n +2 | awk '{print $1}'
    register: command_results
    ignore_errors: yes
    changed_when: false
    tags:
    - helm_purge

  - name: helm delete purge all apps
    environment: '{{env_kc}}'
    command: helm delete --purge {{ item }}
    with_items: "{{ command_results.stdout_lines }}"
    ignore_errors: yes
    tags:
    - helm_purge

  - name: wait till all helm apps are deleted/purged
    shell: helm list | tail -n +2
    register: command_result
    until: command_result.stdout == ""
    retries: 20
    delay: 3
    changed_when: false
    ignore_errors: yes
    tags:
    - helm_purge

  - name: helm remove/cleanup
    environment: '{{env_kc}}'
    shell: ( helm reset || true ) && ( kubectl delete deployment --namespace=kube-system tiller-deploy || true ) && ( kubectl delete service --namespace=kube-system tiller-deploy  || true ) && (  kubectl delete clusterrolebinding tiller  || true ) && (  kubectl delete --namespace=kube-system sa tiller )
    ignore_errors: yes 

  tags:
  - helm_reset
  - reset

